### ISSUE TITLE
Missing Tier 2 Cloud Function Locations?

### ISSUE THREAD

**Issue by rosariopfernandes** [typesense/firestore-typesense-search#1]
## Description

Looking at the current list of possible Cloud Function Locations, I noticed it only offers Tier 1 Cloud Function Locations:

https://github.com/typesense/firestore-typesense-search/blob/ab9291b649a5d0f1d5bb4ffb12324c428a76e479/extension.yaml#L96-L112

But Cloud Functions has many more locations (Tier 2), as shown in their [docs](https://firebase.google.com/docs/functions/locations).

I wonder if this was intenttional? Was it due to the pricing difference between the Tiers?

**Comment by jasonbosco** [comment]
@rosariopfernandes Thank you for pointing this out! I used an example from the extensions developer docs which only had those regions and I (mistakenly) assumed those were the only ones available. I've now added the other regions available in 2123126f0bbbd8f6f35fd4b50707367b9109cdf7. 

Will publish this new version shortly.
