### ISSUE TITLE
Can't install extension via console

### ISSUE THREAD

**Issue by mkarkachov** [typesense/firestore-typesense-search#11]
Please check screenshot. I think this issue is linked with service account permissions but i can find which service account is associated with extension.

![Selection_008](https://user-images.githubusercontent.com/1360242/128420606-8cfeb7c1-009f-487c-afa3-43e334bcd02a.png)

**Comment by i14h** [comment]
@mkarkachov have you enabled Firebase on your project?

**Comment by mkarkachov** [comment]
> @mkarkachov have you enabled Firebase on your project?

ofc, i tried to install extension via console.firebase.google.com

**Comment by mkarkachov** [comment]
> @mkarkachov have you enabled Firebase on your project?

We can close ticket. Service account "Google APIs Service Agent" was missed, not sure how it was happened :) Restored it with Editor role and all works as expected.
