### ISSUE TITLE
Firebase integration with self-hosted server

### ISSUE THREAD

**Issue by echo-slam-jam** [typesense/firestore-typesense-search#12]
## Description

I installed typesense in my 

ubuntu 20.04 apache server 

and it is successfully running but I can't succeed in trying to sync my firestore data using the firebase extension. When I input the public IP of my server in the typesense host portion, it fails to upsert the data.

## Steps to reproduce
firebase extension
![image](https://user-images.githubusercontent.com/53904943/128627527-430ae562-3f67-4d18-bb26-d8d360b31ba8.png)

![image](https://user-images.githubusercontent.com/53904943/128627354-c330d3ee-980e-41af-a090-102229b3aea1.png)

and this is my config file for typesense server

![image](https://user-images.githubusercontent.com/53904943/128627396-85401a3b-a077-4923-af74-cb31c18d13d4.png)

I'm guessing that it needs SSL certification but where do I get my SSL certificates to put in the configs?
Can self-signed work? Can certbot work?

I'm new to this so have mercy on me

""

## Metadata

**Typsense Version**:

**OS**:

**Comment by jasonbosco** [comment]
Those logs seem like they're from before you had changed the port to 443. Could you change the port, restart Typesense and then capture the logs from that point on?

> Request #1628516055899: Request to Node 0 failed due to "ERR_TLS_CERT_ALTNAME_INVALID Hostname/IP does not match certificate's altnames: IP: **my public IP** is not in the cert's list: "

It sounds like you've generated your certificate using a domain name, but you've used your IP address when configuring the Firebase extension. Instead, you want to use the domain name in the Firebase extension - the same domain name you used when generating the SSL cert.

**Comment by echo-slam-jam** [comment]
LOG file
![image](https://user-images.githubusercontent.com/53904943/128795618-b5c99ecf-f1ea-4631-bb9c-6c297193008e.png)

Starting the service
![image](https://user-images.githubusercontent.com/53904943/128795685-b69a9147-608b-4bf4-8784-33ac4cb567a3.png)

My config
; Typesense Configuration

[server]

api-address = xxx.xx.xxx.xxx
api-port = 443
data-dir = /var/lib/typesense
api-key = value here
log-dir = /var/log/typesense
enable-cors = true
ssl-certificate = /etc/letsencrypt/live/domain/cert.pem
ssl-certificate-key = /etc/letsencrypt/live/domain/privkey.pem

**Comment by jasonbosco** [comment]
May I know which cloud provider you’re running this on? It looks like the public IP address is not directly accessible on the instance. May be try using the private IP of the instance for api-address?

**Comment by echo-slam-jam** [comment]
> 
> 
> May I know which cloud provider you’re running this on? It looks like the public IP address is not directly accessible on the instance. May be try using the private IP of the instance for api-address?

The virtual machine is actually owned by the university where I am studying at.
They are also the ones responsible for giving me the public DNS which I used.

I tried the private IP which also didn't work

What might be the cause of this accessibility problem? I can try to bring this up to the manager of the server.

**Comment by echo-slam-jam** [comment]
The server is actually hosted by the university where I study at.

**Comment by jasonbosco** [comment]
Notice how the log [here](https://github.com/typesense/firestore-typesense-search/issues/12#issuecomment-895665185) says "Cannot assign requested IP". That's the underlying issue. 

- When you run `ifconfig` does that show you the public IP? 
- Does `ifconfig` show you an address like `10.x.x.x` or `192.168.x.x`?

**Comment by echo-slam-jam** [comment]
![image](https://user-images.githubusercontent.com/53904943/128807968-ac243bfd-01b2-49c9-a785-5f8ed85f03e0.png)

**Comment by jasonbosco** [comment]
Could you post the logs, once you update the IP address in the Typesense configs to `10.207.9.46` and restart the Typesense process?

**Comment by echo-slam-jam** [comment]
![image](https://user-images.githubusercontent.com/53904943/128809046-88695570-f5fb-4968-a209-144bb67a3050.png)


Ohhhh I can see that it says that the address is already in use

**Comment by jasonbosco** [comment]
Yup, so some other process is already using port 443. You can try `lsof -i :443` to see which process that is.

**Comment by echo-slam-jam** [comment]
![image](https://user-images.githubusercontent.com/53904943/128809797-37590b1b-6294-4256-99c1-2329209eb98c.png)

Hmmm the directory is the same as the directory where I hosted the file storage that I use for serving the files from this server 
So does this mean that I cannot host this service anymore due to that?

**Comment by jasonbosco** [comment]
Ah, if you're already using 443 for Apache, another thing you could do is run Typesense with `http` protocol on say port `8108` (the default). Then setup Apache to handle HTTPS on port 443, and then have Apache reverse proxy to Typesense on port 8108.

**Comment by echo-slam-jam** [comment]
Ohh nice. This is what @britisharmy also suggested.

Are these sets for elasticsearch applicable?
https://devdocs.magento.com/guides/v2.4/install-gde/prereq/es-config-apache.html

**Comment by jasonbosco** [comment]
That link doesn't seem to cover https. This looks more recent and talks about https setup as well: https://www.digitalocean.com/community/tutorials/how-to-use-apache-http-server-as-reverse-proxy-using-mod_proxy-extension

**Comment by echo-slam-jam** [comment]
I see.

Do I need to follow the whole steps starting from **Modifying The Default Configuration**

Or just **Enabling SSL Reverse-Proxy Support**

**Comment by jasonbosco** [comment]
Everything except "Enabling Load-Balancing"

**Comment by echo-slam-jam** [comment]
ok I'll get back to you after I do it

**Comment by echo-slam-jam** [comment]
> 
> 
> That link doesn't seem to cover https. This looks more recent and talks about https setup as well: https://www.digitalocean.com/community/tutorials/how-to-use-apache-http-server-as-reverse-proxy-using-mod_proxy-extension
> 
> The key thing to change in that guide is:
> 
> ```
> ProxyPass / http://0.0.0.0:8080/
> ProxyPassReverse / http://0.0.0.0:8080/
> ```
> 
> becomes
> 
> ```
> ProxyPassReverse / http://0.0.0.0:8108/
> ```
This is my config for the 000-default
<VirtualHost *:*>
    ProxyPreserveHost On

    # Servers to proxy the connection, or;
    # List of application servers:
    # Usage:
    # ProxyPass / http://[IP Addr.]:[port]/
    # ProxyPassReverse / http://[IP Addr.]:[port]/
    # Example:
    ProxyPass / http://10.207.9.46:8108/
    ProxyPassReverse / http://10.207.9.46:8108/

    ServerName localhost
</VirtualHost>

Listen 443

NameVirtualHost *:443
<VirtualHost *:443>

    SSLEngine On

    # Set the path to SSL certificate
    # Usage: SSLCertificateFile /path/to/cert.pem
    SSLCertificateFile /etc/letsencrypt/live/my domain/cert.pem


    # Servers to proxy the connection, or;
    # List of application servers:
    # Usage:
    # ProxyPass / http://[IP Addr.]:[port]/
    # ProxyPassReverse / http://[IP Addr.]:[port]/
    # Example:
    ProxyPass / http://10.207.9.46:8108/
    ProxyPassReverse / http://10.207.9.46:8108/

    # Or, balance the load:
    # ProxyPass / balancer://balancer_cluster_name

</VirtualHost>

I cannot restart apache2 because of the error

![image](https://user-images.githubusercontent.com/53904943/128825004-4e13cf34-9ff7-416d-a1d3-b2628cb2919c.png)

Line 16 is **Listen 443**

**Comment by britisharmy** [comment]
The certificate cant work on a naked ip. You shall need a sub domain or a tld.

**Comment by echo-slam-jam** [comment]
Hmmm

So I managed to successfully restart apache2.
- I removed **Listen 443**
- I removed **NameVirtualHost *:443**

This is now my config for 000-default
<VirtualHost *:*>
    ProxyPreserveHost On

    # Servers to proxy the connection, or;
    # List of application servers:
    # Usage:
    # ProxyPass / http://[IP Addr.]:[port]/
    # ProxyPassReverse / http://[IP Addr.]:[port]/
    # Example:
    ProxyPass / http://10.207.9.46:8108/
    ProxyPassReverse / http://10.207.9.46:8108/

    ServerName localhost
</VirtualHost>
<VirtualHost *:443>

    SSLEngine On

    # Set the path to SSL certificate
    # Usage: SSLCertificateFile /path/to/cert.pem
    SSLCertificateFile /etc/letsencrypt/live/my-domain/cert.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/my-domain/privkey.pem

    # Servers to proxy the connection, or;
    # List of application servers:
    # Usage:
    # ProxyPass / http://[IP Addr.]:[port]/
    # ProxyPassReverse / http://[IP Addr.]:[port]/
    # Example:
    ProxyPass / http://10.207.9.46:8108/
    ProxyPassReverse / http://10.207.9.46:8108/

    # Or, balance the load:
    # ProxyPass / balancer://balancer_cluster_name

</VirtualHost>


And here is my config for typesense

  GNU nano 4.8                                                                            /etc/typesense/typesense-server.ini                                                                                      ; Typesense Configuration

[server]

api-address = 10.207.9.46
api-port = 8108
data-dir = /var/lib/typesense
api-key = value here
log-dir = /var/log/typesense
enable-cors = true

Now both services are running

Are these configs correct?
I can now curl "HTTP://10.207.9.46:8108/health"

I can't curl https version

What should I be able to curl?
How do I verify if my reverse proxy works?

**Comment by jasonbosco** [comment]
You only need 

`ProxyPassReverse / http://10.207.9.46:8108/`

and NOT 

`ProxyPass / http://10.207.9.46:8108/`.


Essentially, the idea is that you're running multiple web-servers behind Apache, one is your existing site, and the other is Typesense. Depending on what hostname shows up in the HTTP headers, Apache will either send the request to your existing site or to Typesense. HTTPS/SSL is handled by Apache and the connection to Typesense uses regular http on port 8108.

In this setup, the idea is that if you've configured say typesense.domain.com to reverse proxy to `http://10.207.9.46:8108`, then, you should be able to curl https://typesense.domain.com/health and Apache will send that request to Typesense internally.

**Comment by echo-slam-jam** [comment]
> 
> 
> You only need
> 
> `ProxyPassReverse / http://10.207.9.46:8108/`
> 
> and NOT
> 
> `ProxyPass / http://10.207.9.46:8108/`.
> 
> Essentially, the idea is that you're running multiple web-servers behind Apache, one is your existing site, and the other is Typesense. Depending on what hostname shows up in the HTTP headers, Apache will either send the request to your existing site or to Typesense. HTTPS/SSL is handled by Apache and the connection to Typesense uses regular http on port 8108.
> 
> In this setup, the idea is that if you've configured say typesense.domain.com to reverse proxy to `http://10.207.9.46:8108`, then, you should be able to curl https://typesense.domain.com/health and Apache will send that request to Typesense internally.

If I understand correctly, do I need to create a subdomain for my domain which I will call, say, "typesense.domain" which I will reverse proxy to http://10.207.9.46:8108 
or can I just use 000-default like what digital ocean did?

**Comment by echo-slam-jam** [comment]
Or can I also do it like this
![image](https://user-images.githubusercontent.com/53904943/128951151-8d1bee54-9ffd-42ce-9f25-5f0d6db2aa74.png)
I will just assign the specific /typesense path to reverse proxy to port 8108

**Comment by jasonbosco** [comment]
Yeah, either of those should work. You might have to do some URL re-writing so Typesense doesn't see the `/typesense/` portion of the URL... Not sure if that's how it works out of the box, or if more configuration is needed in Apache.

**Comment by echo-slam-jam** [comment]
Ok
So I have now successfully configured my reverse proxy and curl "https://mydomain/typesense/health" now returns ok:true
I can also see it through web browser so I assume that this is already working

Now I went to the firebase extension and 

**typesense host**: mydomain/typesense

still returns HTTP error 404
![image](https://user-images.githubusercontent.com/53904943/128961508-c478b05b-f353-4a7c-8ee3-4fef4a1b2be2.png)

so I changed it to 
**typesense host**: mydomain/typesense/collections
because that is where my collection is

but it still returns an error 
![image](https://user-images.githubusercontent.com/53904943/128961583-8da7380b-48d2-4835-b765-69503f21c12d.png)

What should be the correct host?
is there still something missing from my server setup?
This is my reverse proxy setup and I think it works fine
![image](https://user-images.githubusercontent.com/53904943/128961745-d532e2dc-9330-4838-ad90-e893d72068ec.png)

**Comment by jasonbosco** [comment]
Oh hang on, my bad. While Typesense itself can be hosted under a path, the Firebase extension requires Typesense to be hosted on the root domain. So you'd need to create a new virtual host in Apache and move the reverse proxy config under that, and setup a different sub-domain just for Typesense.

**Comment by echo-slam-jam** [comment]
Hmmm let me clarify.

Currently, the process goes like this

extension -> my SSL domain -> reverse proxy to 10.207.9.46:8108
which does not work

Can you illustrate in terms of this process chain?

**Comment by jasonbosco** [comment]
You'd have to set it up this way:

Extension -> https://typesense-sub.domain (setup in Apache as a separate Virtual Host with its own SSL cert) -> reverse proxy to 10.207.9.46:8108

**Comment by echo-slam-jam** [comment]
Hmm can I still use my ssl domain like this?

extension -> https://mydomain/typesense -> reverse proxy to newly created https://typesense -> reverse proxy to 10.207.9.46:8108

**Comment by jasonbosco** [comment]
That won’t work with the Firebase extension. So you need a new domain/sub-domain just for Typesense, but it can still run on the same server.

**Comment by echo-slam-jam** [comment]
Ok I just checked with the server handler and I can fully use the root of mydomain

So now I don't need the subpath anymore and my process now is this:
extension -> my SSL domain (no more subpath) -> reverse proxy to 10.207.9.46:8108

**Comment by echo-slam-jam** [comment]
NICE it is finally working !!!!!
After 4 days of troubleshooting

![image](https://user-images.githubusercontent.com/53904943/128979324-1b7511cd-d13f-4e75-b2cd-8a50ae0aa801.png)

THANKS @jasonbosco and @britisharmy for your assistance :)

Also I noticed that it fails to write empty arrays
Is this as intended?

**Comment by echo-slam-jam** [comment]
> 
> 
> NICE it is finally working !!!!!
> After 4 days of troubleshooting
> 
> ![image](https://user-images.githubusercontent.com/53904943/128979324-1b7511cd-d13f-4e75-b2cd-8a50ae0aa801.png)
> 
> THANKS @jasonbosco and @britisharmy for your assistance :)
> 
> Also I noticed that it fails to write empty arrays
> Is this as intended?

Idk why but now it accepts empty arrays haha

**Comment by jasonbosco** [comment]
Amazing! Kudos to you for your persistence! 🙌 🙌 

It would be awesome if you're able to share the final Apache configs that worked for you, for the benefit of future folks who might stumble on this scenario.

**Comment by echo-slam-jam** [comment]
Sure!

So the process goes like this for me:

Firebase extension -> my SSL (by certbot)  "domain.xxx" -> Reverse proxy to my VM local IP address

My reverse proxy settings on my domain's xxx-le-ssl.conf file

ProxyPreserveHost On
ProxyPass "/" "http://local IP:8108/"
ProxyPassReverse "/" "http://local IP:8108/"
AllowEncodedSlashes On

Then on the firebase extension, use the ssl domain name like "sampledomain.xxx"

Make sure to enable the necessary modules in apache for reverse proxying
https://www.digitalocean.com/community/tutorials/how-to-use-apache-http-server-as-reverse-proxy-using-mod_proxy-extension

Apache docs about reverse proxying that might help understand this stuff
https://httpd.apache.org/docs/2.4/howto/reverse_proxy.html

**Comment by braincomb** [comment]
Is there a reason why Typesense extension doesn't allow to specify a custom port?
