### ISSUE TITLE
How to index Firestore subfields?

### ISSUE THREAD

**Issue by theshadowagent** [typesense/firestore-typesense-search#14]
## Description

I have a Firestore collection with subfields e.g. `{ "user": {"username": string, ...} }` and installed `firestore-typesense-search` extenstion.
I want to create a Typesense collection with indexing by `user.username` without duplicating this in a flat field like `user_username` in Firestore.

Is it possible?
I've tried specifying `user.username,...` in extension configuration, but that doesn't seem to work.

**Comment by jasonbosco** [comment]
Hi @theshadowagent, Typesense doesn't support nested fields at the moment (we're tracking it as part of https://github.com/typesense/typesense/issues/227). So you would have to flatten fields to top-level keys to index them in Typesense. So for eg, `{"user": {"username": string}}` needs to be `{"user_username": string}`.
