### ISSUE TITLE
Firebase cloud function error 

### ISSUE THREAD

**Issue by Nicoglx** [typesense/firestore-typesense-search#16]
## Description

When creating or upserting a document, or a backfill operation the cloud functions fails with the code error "EAI_AGAIN getaddrinfo EAI_AGAIN https". The same issue occurs with both cloud functions (ext-firestore-typesense-search-backfillToTypesenseFromFirestore,  ext-firestore-typesense-search-indexToTypesenseOnFirestoreWrite).
The following are the logs from the cloud function:
- Function execution started
- Creating document {"id":"UMA-NICO-3"}
- Request #1629896880473: Request to Node 0 failed due to "EAI_AGAIN getaddrinfo EAI_AGAIN https"
- Request #1629896880473: Sleeping for 120s and then retrying request...
- Function execution took 120003 ms, finished with status: 'timeout'
I tried running typesense on a virtual machine and typesense cloud, both cases with the same errors.
I also tried creating a collection and a document from a JS client to the typesense cloud and worked fine.
Firebase plan is BLAZE.

## Steps to reproduce

Project created in Firebase, typesense cloud created, cloud function triggered by a new document (or update).

## Expected Behavior

Documents created and updated on typesense cloud.

## Actual Behavior

No documents or collections are synced from Fireabase to typesense cloud.

## Metadata

**Typsense Version**: v0.21.0

**OS**: Linux Ubuntu (used on the VM)

**Comment by renamoo** [comment]
For those who face this error in the future:
`EAI_AGAIN getaddrinfo EAI_AGAIN ` error is usually thrown for the domain. However, error message in the report only shows `https`. It's worth checking if you set the variable `TYPESENSE_HOSTS` correctly. I saw a case where the same error is thrown when `TYPESENSE_HOSTS` is specified with `https://` prefix.

**Comment by alifyandra** [comment]
Hi I have the exact same error "EAI_AGAIN getaddrinfo EAI_AGAIN https" using blaze plan when attempting a backfill or update.
@renamoo Can you elaborate? I'm pretty sure I've input the host name correctly, "https://<myhosthame>".
A fast reply would be very much appreciated as I need to get this to work ASAP for my Uni project deadline.

**Comment by renamoo** [comment]
What I meant is that you should specify domain without https prefix. If your variable includes https, you should remove that.
NG: https://google.com
OK: google.com

**Comment by alifyandra** [comment]
thank you so much @renamoo
