### ISSUE TITLE
Post Install README not linked

### ISSUE THREAD

**Issue by kylewill** [typesense/firestore-typesense-search#2]
After install in Firebase the link to post install instructions links to: https://github.com/typesense/firebase-typesense-search-extension/POSTINSTALL.md which returns a "Not Found" error.

edit: This is after setup and before the install completes. On install the in firebase postinstall docs are displayed. 

During install Firebase links to github with the above "Not Found" url. Not sure if it's a firebase bug?

**Comment by jasonbosco** [comment]
@kylewill Would you be able to share a screenshot of where you see this in the Firebase UI?

**Comment by kylewill** [comment]
Sure - I had to reinstall to get there. 

After setting up the configuration but before the first install completes there's a link here: 

![image](https://user-images.githubusercontent.com/3108182/123878192-a1a96400-d90c-11eb-98ce-b899c00362f4.png)

**Comment by jasonbosco** [comment]
Thanks @kylewill, I've pushed out a fix for this.
