### ISSUE TITLE
Firestore functions doesn't push data to typesense schema

### ISSUE THREAD

**Issue by OCALAB** [typesense/firestore-typesense-search#22]
Hi all!
i've create a typesense schema like this:
`
const myCollection = {
        'name': 'products',
        'fields': [
            {"name": ".*", "type": "auto" }
        ]
    }
`
then, i've installed firestore extension and link "products" schema to a firestore DB collection. But the functions doesn't work. 

When I tried backfill, function throw this error:

![image](https://user-images.githubusercontent.com/44052283/150542294-e5e4aa52-3e94-4325-89f5-7e1a0e5788f4.png)

When I tried to add a document the function doesn't throw an error but in the typesense schema doesn't appear. 
On delete the same document, the function throw this error:

![image](https://user-images.githubusercontent.com/44052283/150541979-68f69b15-2661-4bf3-a49b-13973f5c9d23.png)

It seems that firestore extension cannot comunicate with typesense schema.
Can you help me?

**Comment by jasonbosco** [comment]
@OCALAB Could you share the name of your Firestore collection and also a sample Firestore document?

**Comment by OCALAB** [comment]
Hi @jasonbosco 
I think that this isn't an error that depends on Firestore document structure. I've tryed to push a simple document like 
`{
id: 'Test',
title: 'test'
}`
as you can see on log screenshots, but the same error persist. The collection is called **"Products"**.

I've a self-hosted Typesense. Throught the API i'm able tu push/retrive data correctly.

**Comment by OCALAB** [comment]
Hi @jasonbosco 
Maybe i've found the error. 
In "Host" param of Search Firestore with Typesense extension i've write: mydomain.com:8108. 

In Google Cloud Error Reporting notification i've seen that the function Backfill call an invalid URL _https://mydomain:8108:443/collections/products/documents/import_

![image](https://user-images.githubusercontent.com/44052283/150753167-85e13d96-48cc-4356-92bb-54a7c56ff98e.png)

how can i configure the extension for self-hosted typesense?

**Comment by jasonbosco** [comment]
@OCALAB Good eye! The extension only supports sending data over HTTPS/443 because the data goes from Firestore over the internet to Typesense (regardless of whether its self-hosted or on Typesense Cloud). And we don't want to expose unencrypted data to the public internet. 

Could you get may be LetsEncrypt SSL certs and use that to start your Typesense node on port 443?

**Comment by OCALAB** [comment]
hi @jasonbosco.
I've restart Typesense on port 443 and issued a LetsEncrypt SSL cert. Everything work properly.
Many thanks for you help!
