### ISSUE TITLE
Nodejs 8 upgrade warning

### ISSUE THREAD

**Issue by kylewill** [typesense/firestore-typesense-search#3]
After setup, Firebase displays a warning to upgrade from Node 8 to at least Node 10:

![image](https://user-images.githubusercontent.com/3108182/123860377-d3620100-d8f3-11eb-9fcf-e52ca8f1d35e.png)

**Comment by jasonbosco** [comment]
I heard from the Firebase team that this is a warning that's displayed in the UI for all extensions unfortunately, regardless of the actual node version used. They're working on addressing it. 

The functions deployed by this extension do use Node 14: 

https://github.com/typesense/firestore-typesense-search/blob/c35c0871dc2abed9c0c513f5b4b5fe7023d93d45/extension.yaml#L24
