### ISSUE TITLE
Support for 'ref' type fields

### ISSUE THREAD

**Issue by Guilledorfman** [typesense/firestore-typesense-search#34]
## Description

Currently ref type fields return null:

`else if (value instanceof admin.firestore.DocumentReference) {
    return null;
}`
[See here](https://github.com/typesense/firestore-typesense-search/blob/1b9d22bc1e3fbb55fd548003abbadcbf2be8a3fc/functions/src/utils.js#L16)

## Expected Behavior

`ref` is a firebase object that has a property `path` that returns a string, for me personally that's all I need to be indexed to Typesense so I think working with that would be the easiest solution for now.

## Metadata

**Typsense Version**:

    "typesense": "^1.2.2",
    "typesense-instantsearch-adapter": "^2.4.0"

**OS**:

macOS

**Comment by jasonbosco** [comment]
I've published this in [v0.4.0](https://github.com/typesense/firestore-typesense-search/releases/tag/v0.4.0) of the extension.
