### ISSUE TITLE
Is the backfill batching logic fully correct ?

### ISSUE THREAD

**Issue by sreenath-n** [typesense/firestore-typesense-search#37]
Considering the order of execution of `async` functions in the Node.js Event Loop,
is the backfill batching logic fully correct?

```
let currentDocumentsBatch = [];
querySnapshot.forEach(async ....); // this inner async functions might get executed after next line after the forEach()
if (currentDocumentsBatch.length > 0) { // this line might get executed before above inner async functions
```

**Comment by jasonbosco** [comment]
Thank you for catching this. I was going off of the documentation [here](https://firebase.google.com/docs/firestore/query-data/get-data#get_all_documents_in_a_collection)... but I have indeed run into this issue with `forEach` and async functions in the past. I've gone ahead and pushed out `v0.4.1` of the extension which now uses `for...of` instead.
