### ISSUE TITLE
port and protocol config

### ISSUE THREAD

**Issue by ABC-ACL** [typesense/firestore-typesense-search#39]
Would be nice to be able to configure the server port and protocol.
I have a typesense server on http and port 8108 but can't connect this extension to it, it defaults to https on port 443.

**Comment by jasonbosco** [comment]
This is by design, since Firebase makes calls over the public internet to Typesense and we don't want to expose unencrypted data during transit. More context here: https://github.com/typesense/firestore-typesense-search/issues/4#issuecomment-870957252

**Comment by ABC-ACL** [comment]
Ok, I understand. But that limits the possible server configurations. I can think of a few cases where someone would need to configure a server to listen for https in a non standard port. Or even using http, in the case of the data being 100% public.
