### ISSUE TITLE
Support multiple collections

### ISSUE THREAD

**Issue by 0x80** [typesense/firestore-typesense-search#61]
Reading through the extension docs I conclude that you can only ever have 1 collection synced to Typesense from Firestore. For example the backfill trigger is clearly global and not aware of the collection. That's a bummer because I need multiple.

Is the limitation coming from Firebase Extensions, that you can only have one instance of any type of extension installed?

**Comment by jasonbosco** [comment]
You can indeed sync multiple Firestore collections as described here: https://github.com/typesense/firestore-typesense-search#syncing-multiple-firestore-collections

**Comment by 0x80** [comment]
That's great, thank you!
