### ISSUE TITLE
Support Node.js 18

### ISSUE THREAD

**Issue by alexantonica** [typesense/firestore-typesense-search#62]
## Description

While checking my GCP cloud functions I noticed this
<img width="964" alt="Screenshot 2023-11-01 at 03 05 00" src="https://github.com/typesense/firestore-typesense-search/assets/8859023/72efb9e7-265c-4052-88db-f00022e3b504">

Is supporting v18 coming soon? 

Thank you

**Comment by jasonbosco** [comment]
@alexantonica [This pre-release version](https://github.com/typesense/firestore-typesense-search/releases/tag/v1.2.0-rc.0) has Node 18 support. Could you try installing it using [this installation link](https://console.firebase.google.com/project/_/extensions/install?ref=typesense/firestore-typesense-search@1.2.0-rc.0) and let me know if everything looks ok?

**Comment by alexantonica** [comment]
@jasonbosco the indexing looks ok. Haven't tested the backfilling as the data was already in typesense cluster. 
thank you 🙏

**Comment by luca1s** [comment]
Quick question on this issue and v1.2 rc.0, do you see it becoming a stable release soon?

I've got an app in production using the Firestore plugin (it's amazing, super super well done to the Typesense team) and was hoping to wait for a stable release to switch to Node 18, but I'd definitely be open to upgrading early if you think that might happen after Jan 30.

**Comment by jasonbosco** [comment]
Just waiting for more users to give feedback! Could you install the RC version using the link above, and let me know if it works as expected? 

Once you confirm, happy to promote this build to the GA release.

**Comment by luca1s** [comment]
Just installed it, indexing seems to work perfectly as expected! Didn't backfill since the data was already synced to the Typesense cluster, but everything seems to be working great so far!

**Comment by jasonbosco** [comment]
Thank you for confirming. 

This now released in v1.2.0.
