### ISSUE TITLE
Function Names Generated by Typesense Extensions Are Too Long, Causing Setup Issues in Firebase Locally

### ISSUE THREAD

**Issue by ZakirBangash** [typesense/firestore-typesense-search#64]
## Description

When setting up Firebase Extensions locally, I've encountered a problem related to the length of function names generated by Typesense Extensions. Specifically, the generated functions are named "indexToTypesenseOnFirestoreWrite" and "backfillToTypesenseFromFirestore," and these names exceed the allowable length, causing issues during the local setup process.

## Steps to reproduce

1. Attempt to set up Firebase Extensions locally using the Typesense Extensions.
2. Observe that the function names "indexToTypesenseOnFirestoreWrite" and "backfillToTypesenseFromFirestore" exceed the character limit.
<img width="1030" alt="Screenshot 2023-11-07 at 3 52 39 PM" src="https://github.com/typesense/firestore-typesense-search/assets/66157395/bd9f6436-d186-4036-b2d6-7424cefdac01">

## Expected Behavior
I suggest that Firebase Extensions generated function names adhere to Firebase's function naming constraints, ensuring they are within the allowable character limit.

I would greatly appreciate it if this issue could be addressed as it's currently impeding the local development and deployment of Firebase Extensions using Typesense.

Thank you for your attention to this matter.

**Typesense Version**: typesense/firestore-typesense-search@1.1.0

**Comment by jasonbosco** [comment]
Hmm, that seems new. I just tried this last week and it seems to work fine for me... 

Could you make sure you're using the latest version of firebase-tools? 

If you are, could you share the exact command you're using to start the emulator, so I can try replicating it?

**Comment by jasonbosco** [comment]
I haven't been able to replicate this, but I've still pushed out an update where the function names are shortened in `1.4.0-rc.0`. 

Could you install this pre-release version using [this installation link](https://console.firebase.google.com/project/_/extensions/install?ref=typesense/firestore-typesense-search@1.4.0-rc.0) and let me know if you still see this issue?

**Comment by Ihatetomatoes** [comment]
Thanks @jasonbosco, I had the same issue, but when I change the extension to `1.4.0-rc.0`, I was able to start the emulator without any issues.

<img width="703" alt="image" src="https://github.com/typesense/firestore-typesense-search/assets/735672/11804cff-4820-41e2-9fcb-03a737be3219">

**Comment by jasonbosco** [comment]
Thank you for confirming @Ihatetomatoes! 

Just submitted v1.4.0 to the Firebase extension hub for review.
