### ISSUE TITLE
Fresh plugin installation fails with 401 - a valid `x-typesense-api-key` header must be sent.

### ISSUE THREAD

**Issue by jsancho** [typesense/firestore-typesense-search#73]
## Description
I have just set up a new cluster in Typesense cloud and configured the plugin for a firestore collection.
The process has gone without any issues, it's actually been surprisingly simple.

However, documents are failing to sync due to an authorization issue. 
It seems that the GCF is not setting the header, as the TypeSense host rejects the upsert with the  following message

`RequestUnauthorized: Request failed with HTTP code 401 | Server said: Forbidden - a valid `x-typesense-api-key` header must be sent`

![image](https://github.com/typesense/firestore-typesense-search/assets/1547884/ee2ac64a-de5b-4cf6-a303-015b3cd6f692)

The secret with the API key has been created during the setup, as it can be  seen on the GCF variables tab.

![image](https://github.com/typesense/firestore-typesense-search/assets/1547884/e27acb4b-6443-4c96-bad0-70bde3e218e2)

![image](https://github.com/typesense/firestore-typesense-search/assets/1547884/9c3727be-4520-44d8-9fed-9f4fd8ab0f5a)

I have reviewed the function source and watched for typos for anything related to the `typesenseAPIKey`, that is configured on the client.
It all seems fine to me. 
I was wondering if there might be a little extra to be done when reading secrets from `process.env`.
But if that were the case this would have failed for many others as well.

Do you have any ideas on why this might be failing?

## Steps to reproduce

- Create a new TS cluster
- Configure the firestore TS extension via the web wizard to sync a single collection
- update any document in the collection
- data will not sync, GCF logs will show the error above

## Expected Behavior

I would expect the document to sync to Typesense.

## Actual Behavior

The upsert is rejected with a 401 indicated that the `x-typesense-api-key` has not been provided.

## Metadata

**Typesense Version**: 0.25.2

**OS**: cloud

**Comment by jsancho** [comment]
here's the full stack trace in case this helps

![image](https://github.com/typesense/firestore-typesense-search/assets/1547884/e4da6e24-7648-49b9-aade-477481229a90)

**Comment by jasonbosco** [comment]
Could you make sure that you're using your Typesense Admin API key (and not your search-only api key) when configuring the extension? 

You can verify your API keys' permissions by going to the API Keys section in your Typesense Cloud cluster dashboard (on the right side pane at the bottom).

**Comment by jsancho** [comment]
> Could you make sure that you're using your Typesense Admin API key (and not your search-only api key) when configuring the extension?
> 
> You can verify your API keys' permissions by going to the API Keys section in your Typesense Cloud cluster dashboard (on the right side pane at the bottom).

Yes, the key is one with access to all actions but a restricted set of collections.
![image](https://github.com/typesense/firestore-typesense-search/assets/1547884/67a62f9c-c59c-4fcc-b859-e0d81072a81c)

I have actually used that key to populate the collections initially from a local node project, so it should be fine.

![image](https://github.com/typesense/firestore-typesense-search/assets/1547884/0c92f7f8-0412-4526-86e6-3c70668d88b2)

**Comment by jasonbosco** [comment]
Looks like the `collections` permission is configured incorrectly. 

It either has to be a full verbatim match, or a regex. So if you intend for that API key to allow access to all collections that start with `jsancho_` you want to set it up as `jsanco_.*` in the API key `collections` key

**Comment by jsancho** [comment]
> It either has to be a full verbatim match, or a regex. So if you intend for that API key to allow access to all collections that start with `jsancho_` you want to set it up as `jsanco_.*` in the API key `collections` key
Yikes! that was pretty daft of me.

I'll create some new keys and reconfigure the function. 
I would have sworn that's the key I used to initially populate the collection, but I must have used on of the auto-generated ones at the beginning.

thanks! 🙏🏻

**Comment by jasonbosco** [comment]
Happy to help!
