### ISSUE TITLE
TypeError: value.toDate is not a function while streaming firestore (and backfilling)

### ISSUE THREAD

**Issue by leah-potato** [typesense/firestore-typesense-search#77]
## Description

Getting an error when using the extension with date fields. 

## Steps to reproduce

**1. In Typesense Cloud, create a new collection with auto schema:**

```
{
  "name": "users",  
  "fields": [
    {"name": ".*", "type": "auto" }
  ]
}
```

**2. Install firebase extension (typesense/firestore-typesense-search@1.4.0)**
- Flatten collections: No
- Location: uscental-1

This creates a v1 google function (should it be v2?) and the auto generated schema:
[users.json](https://github.com/typesense/firestore-typesense-search/files/15175910/users.json)

## Expected Behavior

I install the extension and it streams or backfills without errors. 

## Actual Behavior

Logs for (resource.type="cloud_function" resource.labels.function_name=("ext-firestore-typesense-search-indexOnWrite") resource.labels.region="us-central1")** show:

**TypeError: value.toDate is not a function\n    at mapValue (/workspace/src/utils.js:7:29):**
[log_error.json](https://github.com/typesense/firestore-typesense-search/files/15175953/log_error.json)

----

So that's the streaming, but for backfill I kept on getting the same error which caused the function to stop. I had to change the top part of utils.js to get it to run:

```
const config = require("./config.js");
const admin = require("firebase-admin");

const mapValue = (value) => {
  if (typeof value === "object" && value !== null && value._seconds != null && value._nanoseconds != null) {
    // convert Firestore Timestamp to Unix timestamp
    // https://typesense.org/docs/0.22.2/api/collections.html#indexing-dates
    const timestamp = new admin.firestore.Timestamp(value._seconds, value._nanoseconds);
    return Math.floor(timestamp.toDate().getTime() / 1000);
  } else if (typeof value === "object" && value !== null && value.latitude != null && value.longitude != null) {
    return [value.latitude, value.longitude];
  } else if (typeof value === "object" && value !== null && value.firestore != null && value.path != null) {
    return {"path": value.path};
  } else if (Array.isArray(value)) {
    return value.map(mapValue);
  } else if (typeof value === "object" && value !== null) {
    return Object.fromEntries(Object.entries(value).map(([key, value]) => [key, mapValue(value)]));
  } else {
    return value;
  }
};
```

... I think I also had to change to node 14. I can't really remember, it was late at night and if I'm completely honest I'm more of a designer than an engineer 😩

It kept on getting stuck on the lastUpdated (int64) field so I had to reinstall the extension and specifically removed that field. I then successfully backfill 155k documents. Yeah!

I'm sure this is all really basic stuff - apologies. Appreciate any thoughts you have!

## Metadata

**Typesense Version**: Cloud

**Comment by jasonbosco** [comment]
Could you export one sample document from your Firestore collection and share it here?

I wonder if the datatype for that field is somehow not a timestamp...

**Comment by leah-potato** [comment]
They are timestamp fields, ie:

```
createdAt: Timestamp { _seconds: 1713945148, _nanoseconds: 845000000 },
updatedAt: Timestamp { _seconds: 1714475704, _nanoseconds: 262000000 },
lastLogin: Timestamp { _seconds: 1714633329, _nanoseconds: 468000000 }
```

Shouldn't the auto schema account for this?

**Comment by jasonbosco** [comment]
I just tested this in a test Firebase project and I can't seem to replicate the issue. 

This is how my Firestore document looks:

![Screenshot 2024-05-02 at 11 22 17 AM](https://github.com/typesense/firestore-typesense-search/assets/458383/9ab964a1-4e0c-476b-a051-0311f6b18443)

When I click on Edit on the timestamp I see this:

![Screenshot 2024-05-02 at 11 28 27 AM](https://github.com/typesense/firestore-typesense-search/assets/458383/17655bd3-447d-4d69-a875-ea2d72f92983)

Then when I create / update that document, I see this in Typesense:

![Screenshot 2024-05-02 at 11 22 47 AM](https://github.com/typesense/firestore-typesense-search/assets/458383/daec579c-acd2-4453-af55-11954351d925)

This is the schema after the document is inserted:

![Screenshot 2024-05-02 at 11 23 05 AM](https://github.com/typesense/firestore-typesense-search/assets/458383/5e9085d2-701a-4118-8a98-13e02ee0b747)

Could you share a similar set of screenshot with me, from your Firebase project?

**Comment by leah-potato** [comment]
I don't think screenshots are going to help. Lets dig into the detail!

I've narrowed it down to some timestamps not having a nanonseconds value. We've migrated data from another system and it looks like new accounts have it, and old ones don't. 

To account for this, I've modified mapValue with: 

```
if (typeof value === "object" && value !== null && value.seconds != null && value.nanoseconds != null) {
  if (typeof value.toDate === "function") {
    console.log("Using original timestamp calc")
    return Math.floor(value.toDate().getTime() / 1000);
  } else {
    console.log("Issue with timestamp calc. Date Object:", value);
    if (value.nanoseconds && value.nanoseconds !== 0) {
      console.log("Using seconds + nanoseconds as timestamp");
      return Math.floor(value.seconds + value.nanoseconds / 1e9); 
    } else {
      console.log("Using seconds as timestamp");
      return value.seconds;
    }
  }
```

Then I start to see logs with: 
```
{
  "textPayload": "Issue with timestamp calc. Date Object: { seconds: 1693749600, nanoseconds: 0 }",
  "insertId": "6634494f000b6e41014eeba6",
  "resource": {
    "type": "cloud_function",
    "labels": {
      "project_id": "some-project",
      "region": "us-central1",
      "function_name": "ext-users-indexOnWrite"
    }
  },
  "timestamp": "2024-05-03T02:17:51.749121Z",
  "labels": {
    "instance_id": "00f46b9285f91ffd820c2e90d73ad096687fe04272dee4fa14a577bd848d0ab5552a45db5128a79c25bfffce99c179b4e9b8b1417a6ee0d1c5ee070fceb2a907530886",
    "runtime_version": "nodejs18_20240421_18_20_1_RC00",
    "execution_id": "6bpcmsvilk8o"
  },
  "logName": "projects/team-dsc-au/logs/cloudfunctions.googleapis.com%2Fcloud-functions",
  "trace": "projects/team-dsc-au/traces/ec7c445f16baeb75b54c36e567fb5b43",
  "receiveTimestamp": "2024-05-03T02:17:52.044859195Z"
}
```

The backfill across 155k records now works without errors. Nice!

**Comment by leah-potato** [comment]
Now I just need to figure out how to stop the extension to reverting to it's default code. I have just been editing directly into the gcloud functions ui. Any tips on that?

Oh and how to copy the {uid}.id to a new field within typesense {userId} so I can use that field to search.

But progress.

**Comment by jasonbosco** [comment]
> I've narrowed it down to some timestamps not having a nanonseconds value. We've migrated data from another system and it looks like new accounts have it, and old ones don't.

That's interesting to hear. 

> Now I just need to figure out how to stop the extension to reverting to it's default code. I have just been editing directly into the gcloud functions ui. Any tips on that?

I'd recommend just forking the code in this repo and running it in your own Google Cloud function and not use the extension, since you need to modify it. I don't think there's another way to keep the extension and use a modified version just for one portion of the code. 

> Oh and how to copy the {uid}.id to a new field within typesense {userId} so I can use that field to search.

You'd want to do this as part of your forked version of the code as well.

**Comment by leah-potato** [comment]
Makes sense. Thanks for your help and hopefully this thread helps someone someday.
