### ISSUE TITLE
Index a flattened field within an object

### ISSUE THREAD

**Issue by JyYong93** [typesense/firestore-typesense-search#8]
## Description

Hi, I am trying index some fields which are within an object that I am supposed to flatten in order to index in Typesense. But looking at this,
https://github.com/typesense/firestore-typesense-search/blob/master/functions/src/utils.js#L16-L20 , I think even a flattened field would not match. Is there a workaround for fields within an object using firestore & typesense? Thanks in advance.

## Steps to reproduce

Place a flattened field into Firestore Collection Fields.

## Expected Behavior

Index a flattened field within an object into typesense.

## Actual Behavior

Unable to index a flattened field within an object into typesense.

## Metadata

**Typsense Version**:
typesense/firestore-typesense-search@0.2.3

**Comment by jasonbosco** [comment]
The line you linked is meant to filter a subset of keys from your firestore dicument, before indexing them in Typesense. The list of keys to filter comes from the “Firestore Collection Fields” config you specify when installing the extension. 

So it should just work with a flattened key. 

Could you give me an example of a key that doesn’t work, and also a screenshot of the config variables you used in the extension?

**Comment by JyYong93** [comment]
Hi Jason, thanks for the reply. Here is my current setup:

Typesense schema
---
```
const schema = {
  'name': 'hawkers',
  'fields': [
    {'name': 'uuid', 'type': 'string' },
    {'name': 'stallName', 'type': 'string' },
    {'name': 'cuisine', 'type': 'string[]' },
    {'name': 'stallLoc.address', 'type': 'string' }, // Field which I have problem indexing.
    {'name': 'pageView', 'type': 'int32' }
  ],
  'default_sorting_field': 'pageView'
}

```
Firestore document
---
```
{
	...
	"stallLoc": {
		"contact": "",
		"building": "Block 555",
		"address": "Blk 555, Cross Street",
		"postal": "0555",
		"stallUnit": "05-221"
	},
	"cuisine": [
		"Thai",
		"Asian",
		"Noodles",
		"Healthy"
	],
	"pageView": 0,
	"uuid": "506af659-d4f5-43c2-9b4c-a7cd8bc421f6",
	"stallName": "Spicy Kitchen"
}
```

Extension config
---
![image](https://user-images.githubusercontent.com/20752256/126129690-b8be0e2e-8e71-48a9-8751-8d64cc034176.png)


This setup would return the following in the Functions log:
error: 'Field `stallLoc.address` has been declared in the schema, but is not found in the document.', 

I also tried to change up the schema to simply "address" & "stallLoc" and re-running backfilling. But also encountered the following errors:

error: 'Field `address` has been declared in the schema, but is not found in the document.', 
error: 'Field `stallLoc` has been declared in the schema, but is not found in the document.', 

So I am wondering if I am missing some important or doing something wrong?

**Comment by jasonbosco** [comment]
Ah, so you'd need to store the field **pre-flattened** in the Firestore document. So in your example, there needs to be a field called `stallLoc.address` in your Firestore document. The extension itself does not flatten any objects. 

We're planning to add native support for nested fields to Typesense server: https://github.com/typesense/typesense/issues/227. Once that's released, you wouldn't have to do this pre-flattening.

**Comment by JyYong93** [comment]
Understood. Will wait in anticipation until it is supported then. :)

Just another question. So when nested fields are supported, I just need to have a field "stallLoc.address" on the schema and "stallLoc.address" on the firestore collection fields (nothing changes from current setup)?

**Comment by jasonbosco** [comment]
That's right. In fact we're planning to make it even more simple so you'd just need to specify that `stallLoc` is a type of `object` and we'll take care of indexing the nested field with the right data type...

**Comment by JyYong93** [comment]
Got it. Will look forward to the update! Thanks for your time & help again.
