### ISSUE TITLE
Import error TypeError: Right-hand side of 'instanceof' is not callable at Documents.Imported

### ISSUE THREAD

**Issue by driphireweb** [typesense/firestore-typesense-search#83]
## Description
Seems there is a generic type error from javascript when attempting to import a lot of records from firebase

## Steps to reproduce
Attempt to backfill > 1000 records from firebase

## Expected Behavior
```
Done backfilling to Typesense from Firestore
Imported 1000 documents into Typesense
```

## Actual Behavior
```
Done backfilling to Typesense from Firestore
Import error TypeError: Right-hand side of 'instanceof' is not callable at Documents.
Imported 1000 documents into Typesense
```

## Metadata

**Typesense Version**:
0.26

**OS**:
Linux/Ubuntu

**Comment by driphireweb** [comment]
**update** I believe this was due to nested fields having a slightly different structure when streaming to typesense

JSON structure of my entity
```
{
  "geolocation": {
    "geohash": "9q8yyk8yu",
    "latitude": 37.7749295,
    "longitude": -122.4194155
  },
  "location": "San Francisco, CA, USA",
  "workEnvironment": "Hybrid"
}
```

after typesense transform
```
"location": {
  "location": "Chicago, IL, USA",
   "workEnvironment": "Remote",
  "geolocation": [41.8781136,-87.6297982] <---- typesense automatically converts geo
}
```

updated schema
```
    {
      "name": "geolocation",
      "type": "float[]",
      "facet": false,
      "optional": true
    },
```

**Comment by jasonbosco** [comment]
If you're going to be doing geo queries, I would recommend using the `geopoint` data type in Typesense.
