### ISSUE TITLE
Firestore Backfill Not Working

### ISSUE THREAD

**Issue by tapangarg** [typesense/firestore-typesense-search#88]
## Description

Firestore Extension installed, but backfill is not getting triggered. 
## Steps to reproduce

![image](https://github.com/user-attachments/assets/7ab72083-5967-4c70-bcdf-db26b1e163ed)
![image](https://github.com/user-attachments/assets/71b6293d-0006-41a9-896b-c7d5900117fe)

## Expected Behavior
Backfill to trigger and documents to be updated to my notes collection on Typesense

## Actual Behavior

![image](https://github.com/user-attachments/assets/ecddfe44-b9b2-46c2-b3d3-913edb05e419)

## Metadata

**Typesense Version*2.7*:

**OS**:

**Comment by jasonbosco** [comment]
Could you try deleting the trigger key completely from the document and create it again? 

It should still log that missing key error when you delete the key, but when you add it back again, you should now see a 2nd log message stating the backfill is starting and either a success or error messages.

**Comment by tapangarg** [comment]
Thanks Jason. I did this and backfill started, but ended in a crash because of memory.

![Screenshot 2024-09-12 080535](https://github.com/user-attachments/assets/86d9e18a-fd73-4c75-8804-42fa086c3a1c)

**Comment by jasonbosco** [comment]
For large datasets, you would have to run the backfill using an admin script from your local computer. 

We still need to look into batching during backfill as part of #70 to make a cloud function run a large backfill.

**Comment by tapangarg** [comment]
I see. Thank you. Can you point me to some documentation about this?
