### ISSUE TITLE
Add support for multiple collections to be indexed in typesense

### ISSUE THREAD

**Issue by georgekamar** [typesense/firestore-typesense-search#9]
## Description

This is not a bug with the extension, but a request to add a feature that would allow support for multiple collections to be indexed into typesense. The configuration steps could allow an array or list of collections to be inputted, and a subarray for fields.

**Comment by jasonbosco** [comment]
@georgekamar To sync multiple collections, you can actually install this extension multiple times in the same project and set different collection names, in each instance.

**Comment by georgekamar** [comment]
That thought did cross my mind, but I wasnt sure if it was possible, how to manage that, and was hoping there was a way to achieve desired functionality in one installation.

p.s: tried copying the code and modifying locally, but for some reason functions.handler.firestore.document.onWrite(...) does not register as an event, despite it being in firebase's documentation

**Comment by jasonbosco** [comment]
To install a 2nd instance of the extension, you'd just need to click on the Install Extension link in the README file of this repo and select your Firebase project as usual. Firebase will detect that you already have the extension installed and will prompt you to enter a new "extension instance id" like this:

<img width="875" alt="Screen Shot 2021-07-23 at 3 12 34 PM" src="https://user-images.githubusercontent.com/458383/126846335-2c08769b-a504-4dfb-9960-66aece161ec8.png">

Besides that, everything about the installation procedure is the same. 

---

> p.s: tried copying the code and modifying locally, but for some reason functions.handler.firestore.document.onWrite(...) does not register as an event, despite it being in firebase's documentation

IIRC, `functions.handler.firestore` is a Firebase extension specific thing. To write your own handler in a firebase app, you want to use `functions.firestore` like this: https://typesense.org/docs/0.21.0/guide/firebase-full-text-search.html#step-3-write-data-to-typesense

**Comment by georgekamar** [comment]
Thanks for the answers, very helpful !
