### ISSUE TITLE
Running into type issue with decimals in maps

### ISSUE THREAD

**Issue by jrmerril** [typesense/firestore-typesense-search#94]
## Description

In indexOnWrite and backfill, I get the error: "error: 'Field `selectedItem.price` must be an int64.'" whenever selectedItem.price is not an integer value.

## Steps to reproduce

To reproduce, I can add a document into Firestore or run a backfill.

## Expected Behavior

I am supposed to successfully add this document to my Typesense collection.

## Actual Behavior

I fail to upload the document to my Typesense collection.

## Metadata

**Typesense Version**:
Was on 0.24.0, but switched to 27.1 (running docker in my own cloud server), and it still seems to be an issue.
**OS**:

**Comment by jasonbosco** [comment]
> whenever selectedItem.price is not an integer value

I assume you meant to say that sometime this field is `null`? If so, you want to set it as `optional: true` in the collection schema.

**Comment by jrmerril** [comment]
No, it is a decimal sometimes. I thought this may be related so I upgraded to v27, but I'm still getting the issue (https://github.com/typesense/typesense/issues/1327)

**Comment by jasonbosco** [comment]
If it's a decimal sometimes, then you want to define the field type for `selectedItem.price` as `float in the schema.

**Comment by jrmerril** [comment]
Ok thanks. I don't remember setting the schema for it since it's embedded in a map and pulling that map from Firestore. Is there a way for me to get my current schema with an API call?

**Comment by jasonbosco** [comment]
`GET /collections` will get you the schema.

**Comment by jasonbosco** [comment]
You might have to explicitly set the datatype for each sub-field inside the object to prevent this issue, especially if you have mixed datatypes in Firestore. 

Or alternatively, if you're able to set consistent datatypes for each field across documents in Firestore, that would be the best solution.

**Comment by jrmerril** [comment]
Ok that makes sense! Thanks. For now, I've switched it to round to an int for the field and that solves it for me.
